name: Run Gradle on PRs
on: workflow_dispatch
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
    - name: Write lock file
      run: ./gradlew dependencies --write-locks
  build-gradle-project:
    runs-on: ubuntu-latest
    container:
        image: returntocorp/semgrep
    env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
    - name: semgrep scan
      run: semgrep ci

