name: Run Gradle
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  Run Gradle:
  steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v3
  with:
    distribution: 'temurin'
    java-version: '17'
    cache: 'gradle'
- run: ./gradlew build --no-daemon
